mt_domain_navigator.settings:
  mapping:
    domain:
      type: string
      label: 'Domain'
    caption:
      type: string
      label: 'Caption'
    links:
      type: sequence
      label: 'Links'
      sequence:
        type: mapping
        mapping:
          title:
            type: string
            label: 'Title'
          url:
            type: string
            label: 'URL'
    protocol:
      type: string
      label: 'Protocol'